# Generated by Django 6.0.2 on 2026-02-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0002_alter_about_options_alter_about_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=25)),
                ('link', models.URLField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SocialLink',
                'verbose_name_plural': 'SocialLink',
            },
        ),
    ]
